name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      # run: lein deps
      run: |
        ./script/prepare.sh
        lein deps
    - name: Run tests
      run: lein with-profile +cljs test
